#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE Robot Operating System 2 (ROS 2)
#define MW_CONNECTIONINFO_XCPONTCPIP_IPADDRESS ros.codertarget.internal.getExtmodeDeviceAddress(hCS)
#define MW_CONNECTIONINFO_XCPONTCPIP_PORT 17725
#define MW_CONNECTIONINFO_XCPONTCPIP_VERBOSE 0
#define MW_CONNECTIONINFO_TCPIP_IPADDRESS ros.codertarget.internal.getExtmodeDeviceAddress(hCS)
#define MW_CONNECTIONINFO_TCPIP_PORT 17725
#define MW_CONNECTIONINFO_TCPIP_VERBOSE 0
#define MW_CONNECTIONINFO_TCPIP_RUNINBACKGROUND 1
#define MW_EXTMODE_CONFIGURATION XCP on TCP/IP
#define MW_RTOS Linux
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_PACKAGING_MAINTAINERNAME ROS User
#define MW_PACKAGING_MAINTAINEREMAIL ros2user@test.com
#define MW_PACKAGING_LICENSE BSD
#define MW_PACKAGING_VERSION 1.0.0
#define MW_BOARDPARAMETERS_DEVICEADDRESS 
#define MW_BOARDPARAMETERS_USERNAME 
#define MW_ROS_DEPLOYMENTTYPE 0
#define MW_ROS_REMOTEBUILD 1
#define MW_ROS_REFMDLPKG 0
#define MW_ROS_GENERATEROSCONTROL 0
#define MW_ROS_GENERATEROSCOMPONENT 0
#define MW_ROS_ROSTIMESTEPPING 0
#define MW_ROS_ROSTIMENOTIFICATION 0
#define MW_ROS_STEPNOTIFY /step_notify
#define MW_ROS_SUDOREQUIRED 0
#define MW_RUNTIME_BUILDACTION -1
#define MW_ROS2INSTALL_FOLDER /opt/ros/humble
#define MW_ROS2INSTALL_WORKSPACE /Home/Hydro/thresher_auv_ros2
#define MW_EXTMODEINFO_BUFFERSIZE 1000000.000000
#define MW_EXTMODEINFO_TARGETPOLLINGTIME 2
#define MW_CAN_CONFIGURE 0
#define MW_CAN_NUMINTERFACES 0
#define MW_CAN_INTERFACELABEL0 
#define MW_CAN_INTERFACENAME0 can0
#define MW_CAN_INTERFACETYPE0 0
#define MW_CAN_BUSSPEED0 10
#define MW_CAN_TXQUEUESIZE0 65536.000000
#define MW_CAN_INTERFACELABEL1 
#define MW_CAN_INTERFACENAME1 can1
#define MW_CAN_INTERFACETYPE1 0
#define MW_CAN_BUSSPEED1 10
#define MW_CAN_TXQUEUESIZE1 65536.000000
#define MW_CAN_INTERFACELABEL2 
#define MW_CAN_INTERFACENAME2 can2
#define MW_CAN_INTERFACETYPE2 0
#define MW_CAN_BUSSPEED2 10
#define MW_CAN_TXQUEUESIZE2 65536.000000
#define MW_CAN_INTERFACELABEL3 
#define MW_CAN_INTERFACENAME3 can3
#define MW_CAN_INTERFACETYPE3 0
#define MW_CAN_BUSSPEED3 10
#define MW_CAN_TXQUEUESIZE3 65536.000000
#define MW_CAN_INTERFACELABEL4 
#define MW_CAN_INTERFACENAME4 can4
#define MW_CAN_INTERFACETYPE4 0
#define MW_CAN_BUSSPEED4 10
#define MW_CAN_TXQUEUESIZE4 65536.000000
#define MW_CAN_ALLOWALLFILTER 1
#define MW_CAN_BUFFER0IDTYPE 0
#define MW_CAN_ACCEPTANCEMASK0 0
#define MW_CAN_ACCEPTANCEFILTER0 255
#define MW_CAN_INVERSEFILTER0 48
#define MW_CAN_BUFFER1IDTYPE 0
#define MW_CAN_ACCEPTANCEMASK1 0
#define MW_CAN_ACCEPTANCEFILTER1 255
#define MW_CAN_INVERSEFILTER1 48
#define MW_CAN_BUFFER2IDTYPE 0
#define MW_CAN_ACCEPTANCEMASK2 0
#define MW_CAN_ACCEPTANCEFILTER2 255
#define MW_CAN_INVERSEFILTER2 48
#define MW_CAN_BUFFER3IDTYPE 0
#define MW_CAN_ACCEPTANCEMASK3 0
#define MW_CAN_ACCEPTANCEFILTER3 255
#define MW_CAN_INVERSEFILTER3 48
#define MW_DATAVERSION 2016.02

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
